name: Publish Tar to S3
description: Publishes the tarball to an S3 bucket
author: jammy@modern.io

inputs:
  project:
    description: Project name of the tarball
    required: true
runs:
  using: "composite"
  steps:
    # Publish the tarball to S3
    - name: Publish Tarball to S3
      shell: bash
      env:
        PROJECT: ${{ inputs.project }}
        SHA: ${{ github.sha }}
        BUCKET: moderne-labs-spinnaker-distribution
      run: |
        set -e
        
        NEW_KEY="${PROJECT}-${SHA}.tar"
        LOCAL_FILE="${PROJECT}-${SHA}.tar"
        
        echo "Uploading $LOCAL_FILE to s3://$BUCKET/$NEW_KEY"
        aws s3 cp "$LOCAL_FILE" "s3://$BUCKET/$NEW_KEY" --region us-west-2
        
        echo "Searching for previously tagged 'latest' tarball..."
        OBJECTS=$(aws s3api list-objects-v2 \
          --bucket "$BUCKET" \
          --prefix "${PROJECT}-" \
          --query "Contents[].Key" \
          --output text)
        
        for KEY in $OBJECTS; do
          if [ "$KEY" != "$NEW_KEY" ]; then
            TAG=$(aws s3api get-object-tagging \
              --bucket "$BUCKET" \
              --key "$KEY" \
              --query "TagSet[?Key=='latest'].Value" \
              --output text)
        
            if [ "$TAG" == "true" ]; then
              echo "Deleting old 'latest' object: $KEY"
              aws s3 rm "s3://$BUCKET/$KEY"
              break
            fi
          fi
        done
        
        echo "Tagging $NEW_KEY as 'latest'"
        aws s3api put-object-tagging \
          --bucket "$BUCKET" \
          --key "$NEW_KEY" \
          --tagging 'TagSet=[{Key=latest,Value=true}]'