name: Build and Upload Deck

on:
  pull_request:
    types:
      - opened
    branches:
      - main
      - moderne
    paths:
      - 'deck/**'

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Build the distribution
      - name: Build Distribution
        uses: ./.github/actions/moderne/build-deck-distribution

      # Create a tarball of the distribution
      - name: Tar Distribution
        uses: ./.github/actions/moderne/tar-distribution
        with:
          project: deck
          distribution-path: deck/build/webpack

      # Upload the tarball to S3
      - name: Publish Tarball to S3
        uses: ./.github/actions/moderne/publish-s3-bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          project: deck